/**
 */
package PhotosMetaModel.provider;

import PhotosMetaModel.util.PhotosMetaModelAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PhotosMetaModelItemProviderAdapterFactory extends PhotosMetaModelAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PhotosMetaModelItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SoftGallery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SoftGalleryItemProvider softGalleryItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SoftGallery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSoftGalleryAdapter() {
		if (softGalleryItemProvider == null) {
			softGalleryItemProvider = new SoftGalleryItemProvider(this);
		}

		return softGalleryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Domain} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DomainItemProvider domainItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Domain}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDomainAdapter() {
		if (domainItemProvider == null) {
			domainItemProvider = new DomainItemProvider(this);
		}

		return domainItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Architecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArchitectureItemProvider architectureItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Architecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArchitectureAdapter() {
		if (architectureItemProvider == null) {
			architectureItemProvider = new ArchitectureItemProvider(this);
		}

		return architectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Technology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyItemProvider technologyItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Technology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyAdapter() {
		if (technologyItemProvider == null) {
			technologyItemProvider = new TechnologyItemProvider(this);
		}

		return technologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Spring} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpringItemProvider springItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Spring}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpringAdapter() {
		if (springItemProvider == null) {
			springItemProvider = new SpringItemProvider(this);
		}

		return springItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.React} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReactItemProvider reactItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.React}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReactAdapter() {
		if (reactItemProvider == null) {
			reactItemProvider = new ReactItemProvider(this);
		}

		return reactItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Repository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryItemProvider repositoryItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Repository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepositoryAdapter() {
		if (repositoryItemProvider == null) {
			repositoryItemProvider = new RepositoryItemProvider(this);
		}

		return repositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.RestController} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RestControllerItemProvider restControllerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.RestController}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRestControllerAdapter() {
		if (restControllerItemProvider == null) {
			restControllerItemProvider = new RestControllerItemProvider(this);
		}

		return restControllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SpringBootApplication} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpringBootApplicationItemProvider springBootApplicationItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SpringBootApplication}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpringBootApplicationAdapter() {
		if (springBootApplicationItemProvider == null) {
			springBootApplicationItemProvider = new SpringBootApplicationItemProvider(this);
		}

		return springBootApplicationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.RequestMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequestMappingItemProvider requestMappingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.RequestMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequestMappingAdapter() {
		if (requestMappingItemProvider == null) {
			requestMappingItemProvider = new RequestMappingItemProvider(this);
		}

		return requestMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.PostMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostMappingItemProvider postMappingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.PostMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostMappingAdapter() {
		if (postMappingItemProvider == null) {
			postMappingItemProvider = new PostMappingItemProvider(this);
		}

		return postMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.GetMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GetMappingItemProvider getMappingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.GetMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGetMappingAdapter() {
		if (getMappingItemProvider == null) {
			getMappingItemProvider = new GetMappingItemProvider(this);
		}

		return getMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.PutMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PutMappingItemProvider putMappingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.PutMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPutMappingAdapter() {
		if (putMappingItemProvider == null) {
			putMappingItemProvider = new PutMappingItemProvider(this);
		}

		return putMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ExceptionHandler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExceptionHandlerItemProvider exceptionHandlerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ExceptionHandler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExceptionHandlerAdapter() {
		if (exceptionHandlerItemProvider == null) {
			exceptionHandlerItemProvider = new ExceptionHandlerItemProvider(this);
		}

		return exceptionHandlerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.DeleteMapping} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteMappingItemProvider deleteMappingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.DeleteMapping}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteMappingAdapter() {
		if (deleteMappingItemProvider == null) {
			deleteMappingItemProvider = new DeleteMappingItemProvider(this);
		}

		return deleteMappingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.RequestPart} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequestPartItemProvider requestPartItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.RequestPart}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequestPartAdapter() {
		if (requestPartItemProvider == null) {
			requestPartItemProvider = new RequestPartItemProvider(this);
		}

		return requestPartItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Autowired} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AutowiredItemProvider autowiredItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Autowired}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAutowiredAdapter() {
		if (autowiredItemProvider == null) {
			autowiredItemProvider = new AutowiredItemProvider(this);
		}

		return autowiredItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Exception} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExceptionItemProvider exceptionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Exception}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExceptionAdapter() {
		if (exceptionItemProvider == null) {
			exceptionItemProvider = new ExceptionItemProvider(this);
		}

		return exceptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Table_s} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Table_sItemProvider table_sItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Table_s}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTable_sAdapter() {
		if (table_sItemProvider == null) {
			table_sItemProvider = new Table_sItemProvider(this);
		}

		return table_sItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Id} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IdItemProvider idItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Id}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIdAdapter() {
		if (idItemProvider == null) {
			idItemProvider = new IdItemProvider(this);
		}

		return idItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Column_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Column_pItemProvider column_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Column_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumn_pAdapter() {
		if (column_pItemProvider == null) {
			column_pItemProvider = new Column_pItemProvider(this);
		}

		return column_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.GeneratedValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneratedValueItemProvider generatedValueItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.GeneratedValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneratedValueAdapter() {
		if (generatedValueItemProvider == null) {
			generatedValueItemProvider = new GeneratedValueItemProvider(this);
		}

		return generatedValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.NamedNativeQuery} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NamedNativeQueryItemProvider namedNativeQueryItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.NamedNativeQuery}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNamedNativeQueryAdapter() {
		if (namedNativeQueryItemProvider == null) {
			namedNativeQueryItemProvider = new NamedNativeQueryItemProvider(this);
		}

		return namedNativeQueryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Specification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SpecificationItemProvider specificationItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Specification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSpecificationAdapter() {
		if (specificationItemProvider == null) {
			specificationItemProvider = new SpecificationItemProvider(this);
		}

		return specificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SearchCriteria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchCriteriaItemProvider searchCriteriaItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SearchCriteria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchCriteriaAdapter() {
		if (searchCriteriaItemProvider == null) {
			searchCriteriaItemProvider = new SearchCriteriaItemProvider(this);
		}

		return searchCriteriaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Predicate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PredicateItemProvider predicateItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Predicate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPredicateAdapter() {
		if (predicateItemProvider == null) {
			predicateItemProvider = new PredicateItemProvider(this);
		}

		return predicateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Configuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigurationItemProvider configurationItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Configuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigurationAdapter() {
		if (configurationItemProvider == null) {
			configurationItemProvider = new ConfigurationItemProvider(this);
		}

		return configurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Component} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentItemProvider componentItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Component}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentAdapter() {
		if (componentItemProvider == null) {
			componentItemProvider = new ComponentItemProvider(this);
		}

		return componentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Order_s} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Order_sItemProvider order_sItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Order_s}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrder_sAdapter() {
		if (order_sItemProvider == null) {
			order_sItemProvider = new Order_sItemProvider(this);
		}

		return order_sItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.EnableAuthorizationServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnableAuthorizationServerItemProvider enableAuthorizationServerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.EnableAuthorizationServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnableAuthorizationServerAdapter() {
		if (enableAuthorizationServerItemProvider == null) {
			enableAuthorizationServerItemProvider = new EnableAuthorizationServerItemProvider(this);
		}

		return enableAuthorizationServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.EnableResourceServer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnableResourceServerItemProvider enableResourceServerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.EnableResourceServer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnableResourceServerAdapter() {
		if (enableResourceServerItemProvider == null) {
			enableResourceServerItemProvider = new EnableResourceServerItemProvider(this);
		}

		return enableResourceServerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.EnableWebSecurity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnableWebSecurityItemProvider enableWebSecurityItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.EnableWebSecurity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnableWebSecurityAdapter() {
		if (enableWebSecurityItemProvider == null) {
			enableWebSecurityItemProvider = new EnableWebSecurityItemProvider(this);
		}

		return enableWebSecurityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.EnableGlobalMethodSecurity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnableGlobalMethodSecurityItemProvider enableGlobalMethodSecurityItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.EnableGlobalMethodSecurity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnableGlobalMethodSecurityAdapter() {
		if (enableGlobalMethodSecurityItemProvider == null) {
			enableGlobalMethodSecurityItemProvider = new EnableGlobalMethodSecurityItemProvider(this);
		}

		return enableGlobalMethodSecurityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Bean} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BeanItemProvider beanItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Bean}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBeanAdapter() {
		if (beanItemProvider == null) {
			beanItemProvider = new BeanItemProvider(this);
		}

		return beanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.PostgreSQL} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostgreSQLItemProvider postgreSQLItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.PostgreSQL}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostgreSQLAdapter() {
		if (postgreSQLItemProvider == null) {
			postgreSQLItemProvider = new PostgreSQLItemProvider(this);
		}

		return postgreSQLItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Query} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected QueryItemProvider queryItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Query}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createQueryAdapter() {
		if (queryItemProvider == null) {
			queryItemProvider = new QueryItemProvider(this);
		}

		return queryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ForeignKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForeignKeyItemProvider foreignKeyItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ForeignKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForeignKeyAdapter() {
		if (foreignKeyItemProvider == null) {
			foreignKeyItemProvider = new ForeignKeyItemProvider(this);
		}

		return foreignKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Trigger} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TriggerItemProvider triggerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Trigger}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTriggerAdapter() {
		if (triggerItemProvider == null) {
			triggerItemProvider = new TriggerItemProvider(this);
		}

		return triggerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.View} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ViewItemProvider viewItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.View}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createViewAdapter() {
		if (viewItemProvider == null) {
			viewItemProvider = new ViewItemProvider(this);
		}

		return viewItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Index_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Index_pItemProvider index_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Index_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndex_pAdapter() {
		if (index_pItemProvider == null) {
			index_pItemProvider = new Index_pItemProvider(this);
		}

		return index_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Table_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Table_pItemProvider table_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Table_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTable_pAdapter() {
		if (table_pItemProvider == null) {
			table_pItemProvider = new Table_pItemProvider(this);
		}

		return table_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Function_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Function_pItemProvider function_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Function_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunction_pAdapter() {
		if (function_pItemProvider == null) {
			function_pItemProvider = new Function_pItemProvider(this);
		}

		return function_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Database} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatabaseItemProvider databaseItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Database}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatabaseAdapter() {
		if (databaseItemProvider == null) {
			databaseItemProvider = new DatabaseItemProvider(this);
		}

		return databaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Scheme} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SchemeItemProvider schemeItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Scheme}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSchemeAdapter() {
		if (schemeItemProvider == null) {
			schemeItemProvider = new SchemeItemProvider(this);
		}

		return schemeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.User_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected User_pItemProvider user_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.User_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUser_pAdapter() {
		if (user_pItemProvider == null) {
			user_pItemProvider = new User_pItemProvider(this);
		}

		return user_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Cluster} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClusterItemProvider clusterItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Cluster}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClusterAdapter() {
		if (clusterItemProvider == null) {
			clusterItemProvider = new ClusterItemProvider(this);
		}

		return clusterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Row} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RowItemProvider rowItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Row}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRowAdapter() {
		if (rowItemProvider == null) {
			rowItemProvider = new RowItemProvider(this);
		}

		return rowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Column} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ColumnItemProvider columnItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Column}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumnAdapter() {
		if (columnItemProvider == null) {
			columnItemProvider = new ColumnItemProvider(this);
		}

		return columnItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.DataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeItemProvider dataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.DataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeAdapter() {
		if (dataTypeItemProvider == null) {
			dataTypeItemProvider = new DataTypeItemProvider(this);
		}

		return dataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Constraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintItemProvider constraintItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintAdapter() {
		if (constraintItemProvider == null) {
			constraintItemProvider = new ConstraintItemProvider(this);
		}

		return constraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Privilege} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrivilegeItemProvider privilegeItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Privilege}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrivilegeAdapter() {
		if (privilegeItemProvider == null) {
			privilegeItemProvider = new PrivilegeItemProvider(this);
		}

		return privilegeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Policy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PolicyItemProvider policyItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Policy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPolicyAdapter() {
		if (policyItemProvider == null) {
			policyItemProvider = new PolicyItemProvider(this);
		}

		return policyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Clause} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ClauseItemProvider clauseItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Clause}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClauseAdapter() {
		if (clauseItemProvider == null) {
			clauseItemProvider = new ClauseItemProvider(this);
		}

		return clauseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Insert} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InsertItemProvider insertItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Insert}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInsertAdapter() {
		if (insertItemProvider == null) {
			insertItemProvider = new InsertItemProvider(this);
		}

		return insertItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.From} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromItemProvider fromItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.From}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFromAdapter() {
		if (fromItemProvider == null) {
			fromItemProvider = new FromItemProvider(this);
		}

		return fromItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Join} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JoinItemProvider joinItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Join}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJoinAdapter() {
		if (joinItemProvider == null) {
			joinItemProvider = new JoinItemProvider(this);
		}

		return joinItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Lateral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LateralItemProvider lateralItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Lateral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLateralAdapter() {
		if (lateralItemProvider == null) {
			lateralItemProvider = new LateralItemProvider(this);
		}

		return lateralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Where} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WhereItemProvider whereItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Where}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWhereAdapter() {
		if (whereItemProvider == null) {
			whereItemProvider = new WhereItemProvider(this);
		}

		return whereItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.GroupBy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GroupByItemProvider groupByItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.GroupBy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGroupByAdapter() {
		if (groupByItemProvider == null) {
			groupByItemProvider = new GroupByItemProvider(this);
		}

		return groupByItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Having} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HavingItemProvider havingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Having}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHavingAdapter() {
		if (havingItemProvider == null) {
			havingItemProvider = new HavingItemProvider(this);
		}

		return havingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Select} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectItemProvider selectItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Select}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectAdapter() {
		if (selectItemProvider == null) {
			selectItemProvider = new SelectItemProvider(this);
		}

		return selectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Distnct} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DistnctItemProvider distnctItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Distnct}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDistnctAdapter() {
		if (distnctItemProvider == null) {
			distnctItemProvider = new DistnctItemProvider(this);
		}

		return distnctItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Limit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LimitItemProvider limitItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Limit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLimitAdapter() {
		if (limitItemProvider == null) {
			limitItemProvider = new LimitItemProvider(this);
		}

		return limitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Offset} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OffsetItemProvider offsetItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Offset}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOffsetAdapter() {
		if (offsetItemProvider == null) {
			offsetItemProvider = new OffsetItemProvider(this);
		}

		return offsetItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Values} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ValuesItemProvider valuesItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Values}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createValuesAdapter() {
		if (valuesItemProvider == null) {
			valuesItemProvider = new ValuesItemProvider(this);
		}

		return valuesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Alter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AlterItemProvider alterItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Alter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAlterAdapter() {
		if (alterItemProvider == null) {
			alterItemProvider = new AlterItemProvider(this);
		}

		return alterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Delete} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteItemProvider deleteItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Delete}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteAdapter() {
		if (deleteItemProvider == null) {
			deleteItemProvider = new DeleteItemProvider(this);
		}

		return deleteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Create} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateItemProvider createItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Create}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateAdapter() {
		if (createItemProvider == null) {
			createItemProvider = new CreateItemProvider(this);
		}

		return createItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Drop} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DropItemProvider dropItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Drop}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDropAdapter() {
		if (dropItemProvider == null) {
			dropItemProvider = new DropItemProvider(this);
		}

		return dropItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Using} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsingItemProvider usingItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Using}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsingAdapter() {
		if (usingItemProvider == null) {
			usingItemProvider = new UsingItemProvider(this);
		}

		return usingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Index} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IndexItemProvider indexItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Index}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIndexAdapter() {
		if (indexItemProvider == null) {
			indexItemProvider = new IndexItemProvider(this);
		}

		return indexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Update} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateItemProvider updateItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Update}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateAdapter() {
		if (updateItemProvider == null) {
			updateItemProvider = new UpdateItemProvider(this);
		}

		return updateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Array} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayItemProvider arrayItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Array}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayAdapter() {
		if (arrayItemProvider == null) {
			arrayItemProvider = new ArrayItemProvider(this);
		}

		return arrayItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Into} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntoItemProvider intoItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Into}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntoAdapter() {
		if (intoItemProvider == null) {
			intoItemProvider = new IntoItemProvider(this);
		}

		return intoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Column_s} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Column_sItemProvider column_sItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Column_s}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createColumn_sAdapter() {
		if (column_sItemProvider == null) {
			column_sItemProvider = new Column_sItemProvider(this);
		}

		return column_sItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Order_p} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Order_pItemProvider order_pItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Order_p}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrder_pAdapter() {
		if (order_pItemProvider == null) {
			order_pItemProvider = new Order_pItemProvider(this);
		}

		return order_pItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Usuario} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UsuarioItemProvider usuarioItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Usuario}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUsuarioAdapter() {
		if (usuarioItemProvider == null) {
			usuarioItemProvider = new UsuarioItemProvider(this);
		}

		return usuarioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Autenticacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AutenticacionItemProvider autenticacionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Autenticacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAutenticacionAdapter() {
		if (autenticacionItemProvider == null) {
			autenticacionItemProvider = new AutenticacionItemProvider(this);
		}

		return autenticacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Registro} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegistroItemProvider registroItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Registro}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegistroAdapter() {
		if (registroItemProvider == null) {
			registroItemProvider = new RegistroItemProvider(this);
		}

		return registroItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ManejoPerfil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ManejoPerfilItemProvider manejoPerfilItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ManejoPerfil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createManejoPerfilAdapter() {
		if (manejoPerfilItemProvider == null) {
			manejoPerfilItemProvider = new ManejoPerfilItemProvider(this);
		}

		return manejoPerfilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Accion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccionItemProvider accionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Accion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccionAdapter() {
		if (accionItemProvider == null) {
			accionItemProvider = new AccionItemProvider(this);
		}

		return accionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.CrearAlbum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CrearAlbumItemProvider crearAlbumItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.CrearAlbum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCrearAlbumAdapter() {
		if (crearAlbumItemProvider == null) {
			crearAlbumItemProvider = new CrearAlbumItemProvider(this);
		}

		return crearAlbumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.VerAlbum} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VerAlbumItemProvider verAlbumItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.VerAlbum}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVerAlbumAdapter() {
		if (verAlbumItemProvider == null) {
			verAlbumItemProvider = new VerAlbumItemProvider(this);
		}

		return verAlbumItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.CargarFoto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CargarFotoItemProvider cargarFotoItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.CargarFoto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCargarFotoAdapter() {
		if (cargarFotoItemProvider == null) {
			cargarFotoItemProvider = new CargarFotoItemProvider(this);
		}

		return cargarFotoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.VerTodasLasFotos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VerTodasLasFotosItemProvider verTodasLasFotosItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.VerTodasLasFotos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVerTodasLasFotosAdapter() {
		if (verTodasLasFotosItemProvider == null) {
			verTodasLasFotosItemProvider = new VerTodasLasFotosItemProvider(this);
		}

		return verTodasLasFotosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.EditarPerfil} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EditarPerfilItemProvider editarPerfilItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.EditarPerfil}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEditarPerfilAdapter() {
		if (editarPerfilItemProvider == null) {
			editarPerfilItemProvider = new EditarPerfilItemProvider(this);
		}

		return editarPerfilItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Foto} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FotoItemProvider fotoItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Foto}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFotoAdapter() {
		if (fotoItemProvider == null) {
			fotoItemProvider = new FotoItemProvider(this);
		}

		return fotoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Categoria} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CategoriaItemProvider categoriaItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Categoria}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCategoriaAdapter() {
		if (categoriaItemProvider == null) {
			categoriaItemProvider = new CategoriaItemProvider(this);
		}

		return categoriaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Imagen} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImagenItemProvider imagenItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Imagen}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImagenAdapter() {
		if (imagenItemProvider == null) {
			imagenItemProvider = new ImagenItemProvider(this);
		}

		return imagenItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonWebServices} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonWebServicesItemProvider amazonWebServicesItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonWebServices}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonWebServicesAdapter() {
		if (amazonWebServicesItemProvider == null) {
			amazonWebServicesItemProvider = new AmazonWebServicesItemProvider(this);
		}

		return amazonWebServicesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.NTier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NTierItemProvider nTierItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.NTier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNTierAdapter() {
		if (nTierItemProvider == null) {
			nTierItemProvider = new NTierItemProvider(this);
		}

		return nTierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Capa} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CapaItemProvider capaItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Capa}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCapaAdapter() {
		if (capaItemProvider == null) {
			capaItemProvider = new CapaItemProvider(this);
		}

		return capaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Conexion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConexionItemProvider conexionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Conexion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConexionAdapter() {
		if (conexionItemProvider == null) {
			conexionItemProvider = new ConexionItemProvider(this);
		}

		return conexionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Relacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RelacionItemProvider relacionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Relacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRelacionAdapter() {
		if (relacionItemProvider == null) {
			relacionItemProvider = new RelacionItemProvider(this);
		}

		return relacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.REST} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RESTItemProvider restItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.REST}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRESTAdapter() {
		if (restItemProvider == null) {
			restItemProvider = new RESTItemProvider(this);
		}

		return restItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ConexionPostgreSQL} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConexionPostgreSQLItemProvider conexionPostgreSQLItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ConexionPostgreSQL}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConexionPostgreSQLAdapter() {
		if (conexionPostgreSQLItemProvider == null) {
			conexionPostgreSQLItemProvider = new ConexionPostgreSQLItemProvider(this);
		}

		return conexionPostgreSQLItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonS3API} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonS3APIItemProvider amazonS3APIItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonS3API}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonS3APIAdapter() {
		if (amazonS3APIItemProvider == null) {
			amazonS3APIItemProvider = new AmazonS3APIItemProvider(this);
		}

		return amazonS3APIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Presentacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PresentacionItemProvider presentacionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Presentacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPresentacionAdapter() {
		if (presentacionItemProvider == null) {
			presentacionItemProvider = new PresentacionItemProvider(this);
		}

		return presentacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.LogicaDeNegocio} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicaDeNegocioItemProvider logicaDeNegocioItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.LogicaDeNegocio}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicaDeNegocioAdapter() {
		if (logicaDeNegocioItemProvider == null) {
			logicaDeNegocioItemProvider = new LogicaDeNegocioItemProvider(this);
		}

		return logicaDeNegocioItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Datos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatosItemProvider datosItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Datos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatosAdapter() {
		if (datosItemProvider == null) {
			datosItemProvider = new DatosItemProvider(this);
		}

		return datosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AllowedToUse} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AllowedToUseItemProvider allowedToUseItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AllowedToUse}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAllowedToUseAdapter() {
		if (allowedToUseItemProvider == null) {
			allowedToUseItemProvider = new AllowedToUseItemProvider(this);
		}

		return allowedToUseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SegmentoPresentacion} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SegmentoPresentacionItemProvider segmentoPresentacionItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SegmentoPresentacion}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSegmentoPresentacionAdapter() {
		if (segmentoPresentacionItemProvider == null) {
			segmentoPresentacionItemProvider = new SegmentoPresentacionItemProvider(this);
		}

		return segmentoPresentacionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SegmentoLogica} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SegmentoLogicaItemProvider segmentoLogicaItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SegmentoLogica}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSegmentoLogicaAdapter() {
		if (segmentoLogicaItemProvider == null) {
			segmentoLogicaItemProvider = new SegmentoLogicaItemProvider(this);
		}

		return segmentoLogicaItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.SegmentoDatos} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SegmentoDatosItemProvider segmentoDatosItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.SegmentoDatos}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSegmentoDatosAdapter() {
		if (segmentoDatosItemProvider == null) {
			segmentoDatosItemProvider = new SegmentoDatosItemProvider(this);
		}

		return segmentoDatosItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.View_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected View_aItemProvider view_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.View_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createView_aAdapter() {
		if (view_aItemProvider == null) {
			view_aItemProvider = new View_aItemProvider(this);
		}

		return view_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Component_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Component_aItemProvider component_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Component_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponent_aAdapter() {
		if (component_aItemProvider == null) {
			component_aItemProvider = new Component_aItemProvider(this);
		}

		return component_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Action_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Action_aItemProvider action_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Action_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAction_aAdapter() {
		if (action_aItemProvider == null) {
			action_aItemProvider = new Action_aItemProvider(this);
		}

		return action_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Controller_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Controller_aItemProvider controller_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Controller_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createController_aAdapter() {
		if (controller_aItemProvider == null) {
			controller_aItemProvider = new Controller_aItemProvider(this);
		}

		return controller_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Model_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Model_aItemProvider model_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Model_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModel_aAdapter() {
		if (model_aItemProvider == null) {
			model_aItemProvider = new Model_aItemProvider(this);
		}

		return model_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Repository_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Repository_aItemProvider repository_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Repository_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepository_aAdapter() {
		if (repository_aItemProvider == null) {
			repository_aItemProvider = new Repository_aItemProvider(this);
		}

		return repository_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Security_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Security_aItemProvider security_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Security_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecurity_aAdapter() {
		if (security_aItemProvider == null) {
			security_aItemProvider = new Security_aItemProvider(this);
		}

		return security_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.PostgreSQL_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PostgreSQL_aItemProvider postgreSQL_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.PostgreSQL_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPostgreSQL_aAdapter() {
		if (postgreSQL_aItemProvider == null) {
			postgreSQL_aItemProvider = new PostgreSQL_aItemProvider(this);
		}

		return postgreSQL_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonS3Storage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonS3StorageItemProvider amazonS3StorageItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonS3Storage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonS3StorageAdapter() {
		if (amazonS3StorageItemProvider == null) {
			amazonS3StorageItemProvider = new AmazonS3StorageItemProvider(this);
		}

		return amazonS3StorageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ReactDOM} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReactDOMItemProvider reactDOMItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ReactDOM}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReactDOMAdapter() {
		if (reactDOMItemProvider == null) {
			reactDOMItemProvider = new ReactDOMItemProvider(this);
		}

		return reactDOMItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Element_r} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Element_rItemProvider element_rItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Element_r}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElement_rAdapter() {
		if (element_rItemProvider == null) {
			element_rItemProvider = new Element_rItemProvider(this);
		}

		return element_rItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Component_r} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Component_rItemProvider component_rItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Component_r}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponent_rAdapter() {
		if (component_rItemProvider == null) {
			component_rItemProvider = new Component_rItemProvider(this);
		}

		return component_rItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Prop} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PropItemProvider propItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Prop}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPropAdapter() {
		if (propItemProvider == null) {
			propItemProvider = new PropItemProvider(this);
		}

		return propItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Class_r} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Class_rItemProvider class_rItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Class_r}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createClass_rAdapter() {
		if (class_rItemProvider == null) {
			class_rItemProvider = new Class_rItemProvider(this);
		}

		return class_rItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Function_r} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Function_rItemProvider function_rItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Function_r}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunction_rAdapter() {
		if (function_rItemProvider == null) {
			function_rItemProvider = new Function_rItemProvider(this);
		}

		return function_rItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Render} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RenderItemProvider renderItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Render}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRenderAdapter() {
		if (renderItemProvider == null) {
			renderItemProvider = new RenderItemProvider(this);
		}

		return renderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Constructor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstructorItemProvider constructorItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Constructor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstructorAdapter() {
		if (constructorItemProvider == null) {
			constructorItemProvider = new ConstructorItemProvider(this);
		}

		return constructorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ComponentDidMount} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentDidMountItemProvider componentDidMountItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ComponentDidMount}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentDidMountAdapter() {
		if (componentDidMountItemProvider == null) {
			componentDidMountItemProvider = new ComponentDidMountItemProvider(this);
		}

		return componentDidMountItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ComponentWillUnmount} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComponentWillUnmountItemProvider componentWillUnmountItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ComponentWillUnmount}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComponentWillUnmountAdapter() {
		if (componentWillUnmountItemProvider == null) {
			componentWillUnmountItemProvider = new ComponentWillUnmountItemProvider(this);
		}

		return componentWillUnmountItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonElasticComputeCloud} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonElasticComputeCloudItemProvider amazonElasticComputeCloudItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonElasticComputeCloud}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonElasticComputeCloudAdapter() {
		if (amazonElasticComputeCloudItemProvider == null) {
			amazonElasticComputeCloudItemProvider = new AmazonElasticComputeCloudItemProvider(this);
		}

		return amazonElasticComputeCloudItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonSimpleStorageService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonSimpleStorageServiceItemProvider amazonSimpleStorageServiceItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonSimpleStorageService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonSimpleStorageServiceAdapter() {
		if (amazonSimpleStorageServiceItemProvider == null) {
			amazonSimpleStorageServiceItemProvider = new AmazonSimpleStorageServiceItemProvider(this);
		}

		return amazonSimpleStorageServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonAurora} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonAuroraItemProvider amazonAuroraItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonAurora}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonAuroraAdapter() {
		if (amazonAuroraItemProvider == null) {
			amazonAuroraItemProvider = new AmazonAuroraItemProvider(this);
		}

		return amazonAuroraItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonDynamoDB} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonDynamoDBItemProvider amazonDynamoDBItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonDynamoDB}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonDynamoDBAdapter() {
		if (amazonDynamoDBItemProvider == null) {
			amazonDynamoDBItemProvider = new AmazonDynamoDBItemProvider(this);
		}

		return amazonDynamoDBItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.AmazonSageMaker} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AmazonSageMakerItemProvider amazonSageMakerItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.AmazonSageMaker}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAmazonSageMakerAdapter() {
		if (amazonSageMakerItemProvider == null) {
			amazonSageMakerItemProvider = new AmazonSageMakerItemProvider(this);
		}

		return amazonSageMakerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Bucket} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BucketItemProvider bucketItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Bucket}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBucketAdapter() {
		if (bucketItemProvider == null) {
			bucketItemProvider = new BucketItemProvider(this);
		}

		return bucketItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.BatchOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BatchOperationItemProvider batchOperationItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.BatchOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBatchOperationAdapter() {
		if (batchOperationItemProvider == null) {
			batchOperationItemProvider = new BatchOperationItemProvider(this);
		}

		return batchOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Access} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AccessItemProvider accessItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Access}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAccessAdapter() {
		if (accessItemProvider == null) {
			accessItemProvider = new AccessItemProvider(this);
		}

		return accessItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Public} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PublicItemProvider publicItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Public}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPublicAdapter() {
		if (publicItemProvider == null) {
			publicItemProvider = new PublicItemProvider(this);
		}

		return publicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.ObjectsPublic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectsPublicItemProvider objectsPublicItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.ObjectsPublic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectsPublicAdapter() {
		if (objectsPublicItemProvider == null) {
			objectsPublicItemProvider = new ObjectsPublicItemProvider(this);
		}

		return objectsPublicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.BucketObjectsNotPublic} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BucketObjectsNotPublicItemProvider bucketObjectsNotPublicItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.BucketObjectsNotPublic}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBucketObjectsNotPublicAdapter() {
		if (bucketObjectsNotPublicItemProvider == null) {
			bucketObjectsNotPublicItemProvider = new BucketObjectsNotPublicItemProvider(this);
		}

		return bucketObjectsNotPublicItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.OnlyAuthorized} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OnlyAuthorizedItemProvider onlyAuthorizedItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.OnlyAuthorized}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOnlyAuthorizedAdapter() {
		if (onlyAuthorizedItemProvider == null) {
			onlyAuthorizedItemProvider = new OnlyAuthorizedItemProvider(this);
		}

		return onlyAuthorizedItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.File_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected File_aItemProvider file_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.File_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFile_aAdapter() {
		if (file_aItemProvider == null) {
			file_aItemProvider = new File_aItemProvider(this);
		}

		return file_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.Folder_a} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Folder_aItemProvider folder_aItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.Folder_a}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFolder_aAdapter() {
		if (folder_aItemProvider == null) {
			folder_aItemProvider = new Folder_aItemProvider(this);
		}

		return folder_aItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link PhotosMetaModel.MetaData} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MetaDataItemProvider metaDataItemProvider;

	/**
	 * This creates an adapter for a {@link PhotosMetaModel.MetaData}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMetaDataAdapter() {
		if (metaDataItemProvider == null) {
			metaDataItemProvider = new MetaDataItemProvider(this);
		}

		return metaDataItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (softGalleryItemProvider != null) softGalleryItemProvider.dispose();
		if (domainItemProvider != null) domainItemProvider.dispose();
		if (architectureItemProvider != null) architectureItemProvider.dispose();
		if (technologyItemProvider != null) technologyItemProvider.dispose();
		if (springItemProvider != null) springItemProvider.dispose();
		if (reactItemProvider != null) reactItemProvider.dispose();
		if (repositoryItemProvider != null) repositoryItemProvider.dispose();
		if (restControllerItemProvider != null) restControllerItemProvider.dispose();
		if (springBootApplicationItemProvider != null) springBootApplicationItemProvider.dispose();
		if (requestMappingItemProvider != null) requestMappingItemProvider.dispose();
		if (postMappingItemProvider != null) postMappingItemProvider.dispose();
		if (getMappingItemProvider != null) getMappingItemProvider.dispose();
		if (putMappingItemProvider != null) putMappingItemProvider.dispose();
		if (exceptionHandlerItemProvider != null) exceptionHandlerItemProvider.dispose();
		if (deleteMappingItemProvider != null) deleteMappingItemProvider.dispose();
		if (requestPartItemProvider != null) requestPartItemProvider.dispose();
		if (autowiredItemProvider != null) autowiredItemProvider.dispose();
		if (exceptionItemProvider != null) exceptionItemProvider.dispose();
		if (entityItemProvider != null) entityItemProvider.dispose();
		if (table_sItemProvider != null) table_sItemProvider.dispose();
		if (idItemProvider != null) idItemProvider.dispose();
		if (column_pItemProvider != null) column_pItemProvider.dispose();
		if (generatedValueItemProvider != null) generatedValueItemProvider.dispose();
		if (namedNativeQueryItemProvider != null) namedNativeQueryItemProvider.dispose();
		if (specificationItemProvider != null) specificationItemProvider.dispose();
		if (searchCriteriaItemProvider != null) searchCriteriaItemProvider.dispose();
		if (predicateItemProvider != null) predicateItemProvider.dispose();
		if (configurationItemProvider != null) configurationItemProvider.dispose();
		if (componentItemProvider != null) componentItemProvider.dispose();
		if (order_sItemProvider != null) order_sItemProvider.dispose();
		if (enableAuthorizationServerItemProvider != null) enableAuthorizationServerItemProvider.dispose();
		if (enableResourceServerItemProvider != null) enableResourceServerItemProvider.dispose();
		if (enableWebSecurityItemProvider != null) enableWebSecurityItemProvider.dispose();
		if (enableGlobalMethodSecurityItemProvider != null) enableGlobalMethodSecurityItemProvider.dispose();
		if (beanItemProvider != null) beanItemProvider.dispose();
		if (postgreSQLItemProvider != null) postgreSQLItemProvider.dispose();
		if (queryItemProvider != null) queryItemProvider.dispose();
		if (foreignKeyItemProvider != null) foreignKeyItemProvider.dispose();
		if (triggerItemProvider != null) triggerItemProvider.dispose();
		if (viewItemProvider != null) viewItemProvider.dispose();
		if (index_pItemProvider != null) index_pItemProvider.dispose();
		if (table_pItemProvider != null) table_pItemProvider.dispose();
		if (function_pItemProvider != null) function_pItemProvider.dispose();
		if (databaseItemProvider != null) databaseItemProvider.dispose();
		if (schemeItemProvider != null) schemeItemProvider.dispose();
		if (user_pItemProvider != null) user_pItemProvider.dispose();
		if (clusterItemProvider != null) clusterItemProvider.dispose();
		if (rowItemProvider != null) rowItemProvider.dispose();
		if (columnItemProvider != null) columnItemProvider.dispose();
		if (dataTypeItemProvider != null) dataTypeItemProvider.dispose();
		if (constraintItemProvider != null) constraintItemProvider.dispose();
		if (privilegeItemProvider != null) privilegeItemProvider.dispose();
		if (policyItemProvider != null) policyItemProvider.dispose();
		if (clauseItemProvider != null) clauseItemProvider.dispose();
		if (insertItemProvider != null) insertItemProvider.dispose();
		if (fromItemProvider != null) fromItemProvider.dispose();
		if (joinItemProvider != null) joinItemProvider.dispose();
		if (lateralItemProvider != null) lateralItemProvider.dispose();
		if (whereItemProvider != null) whereItemProvider.dispose();
		if (groupByItemProvider != null) groupByItemProvider.dispose();
		if (havingItemProvider != null) havingItemProvider.dispose();
		if (selectItemProvider != null) selectItemProvider.dispose();
		if (distnctItemProvider != null) distnctItemProvider.dispose();
		if (limitItemProvider != null) limitItemProvider.dispose();
		if (offsetItemProvider != null) offsetItemProvider.dispose();
		if (valuesItemProvider != null) valuesItemProvider.dispose();
		if (alterItemProvider != null) alterItemProvider.dispose();
		if (deleteItemProvider != null) deleteItemProvider.dispose();
		if (createItemProvider != null) createItemProvider.dispose();
		if (dropItemProvider != null) dropItemProvider.dispose();
		if (usingItemProvider != null) usingItemProvider.dispose();
		if (indexItemProvider != null) indexItemProvider.dispose();
		if (updateItemProvider != null) updateItemProvider.dispose();
		if (arrayItemProvider != null) arrayItemProvider.dispose();
		if (intoItemProvider != null) intoItemProvider.dispose();
		if (column_sItemProvider != null) column_sItemProvider.dispose();
		if (order_pItemProvider != null) order_pItemProvider.dispose();
		if (usuarioItemProvider != null) usuarioItemProvider.dispose();
		if (autenticacionItemProvider != null) autenticacionItemProvider.dispose();
		if (registroItemProvider != null) registroItemProvider.dispose();
		if (manejoPerfilItemProvider != null) manejoPerfilItemProvider.dispose();
		if (accionItemProvider != null) accionItemProvider.dispose();
		if (crearAlbumItemProvider != null) crearAlbumItemProvider.dispose();
		if (verAlbumItemProvider != null) verAlbumItemProvider.dispose();
		if (cargarFotoItemProvider != null) cargarFotoItemProvider.dispose();
		if (verTodasLasFotosItemProvider != null) verTodasLasFotosItemProvider.dispose();
		if (editarPerfilItemProvider != null) editarPerfilItemProvider.dispose();
		if (fotoItemProvider != null) fotoItemProvider.dispose();
		if (categoriaItemProvider != null) categoriaItemProvider.dispose();
		if (imagenItemProvider != null) imagenItemProvider.dispose();
		if (amazonWebServicesItemProvider != null) amazonWebServicesItemProvider.dispose();
		if (nTierItemProvider != null) nTierItemProvider.dispose();
		if (capaItemProvider != null) capaItemProvider.dispose();
		if (conexionItemProvider != null) conexionItemProvider.dispose();
		if (relacionItemProvider != null) relacionItemProvider.dispose();
		if (restItemProvider != null) restItemProvider.dispose();
		if (conexionPostgreSQLItemProvider != null) conexionPostgreSQLItemProvider.dispose();
		if (amazonS3APIItemProvider != null) amazonS3APIItemProvider.dispose();
		if (presentacionItemProvider != null) presentacionItemProvider.dispose();
		if (logicaDeNegocioItemProvider != null) logicaDeNegocioItemProvider.dispose();
		if (datosItemProvider != null) datosItemProvider.dispose();
		if (allowedToUseItemProvider != null) allowedToUseItemProvider.dispose();
		if (segmentoPresentacionItemProvider != null) segmentoPresentacionItemProvider.dispose();
		if (segmentoLogicaItemProvider != null) segmentoLogicaItemProvider.dispose();
		if (segmentoDatosItemProvider != null) segmentoDatosItemProvider.dispose();
		if (view_aItemProvider != null) view_aItemProvider.dispose();
		if (component_aItemProvider != null) component_aItemProvider.dispose();
		if (action_aItemProvider != null) action_aItemProvider.dispose();
		if (controller_aItemProvider != null) controller_aItemProvider.dispose();
		if (model_aItemProvider != null) model_aItemProvider.dispose();
		if (repository_aItemProvider != null) repository_aItemProvider.dispose();
		if (security_aItemProvider != null) security_aItemProvider.dispose();
		if (postgreSQL_aItemProvider != null) postgreSQL_aItemProvider.dispose();
		if (amazonS3StorageItemProvider != null) amazonS3StorageItemProvider.dispose();
		if (reactDOMItemProvider != null) reactDOMItemProvider.dispose();
		if (element_rItemProvider != null) element_rItemProvider.dispose();
		if (component_rItemProvider != null) component_rItemProvider.dispose();
		if (propItemProvider != null) propItemProvider.dispose();
		if (class_rItemProvider != null) class_rItemProvider.dispose();
		if (function_rItemProvider != null) function_rItemProvider.dispose();
		if (renderItemProvider != null) renderItemProvider.dispose();
		if (constructorItemProvider != null) constructorItemProvider.dispose();
		if (componentDidMountItemProvider != null) componentDidMountItemProvider.dispose();
		if (componentWillUnmountItemProvider != null) componentWillUnmountItemProvider.dispose();
		if (amazonElasticComputeCloudItemProvider != null) amazonElasticComputeCloudItemProvider.dispose();
		if (amazonSimpleStorageServiceItemProvider != null) amazonSimpleStorageServiceItemProvider.dispose();
		if (amazonAuroraItemProvider != null) amazonAuroraItemProvider.dispose();
		if (amazonDynamoDBItemProvider != null) amazonDynamoDBItemProvider.dispose();
		if (amazonSageMakerItemProvider != null) amazonSageMakerItemProvider.dispose();
		if (bucketItemProvider != null) bucketItemProvider.dispose();
		if (batchOperationItemProvider != null) batchOperationItemProvider.dispose();
		if (accessItemProvider != null) accessItemProvider.dispose();
		if (publicItemProvider != null) publicItemProvider.dispose();
		if (objectsPublicItemProvider != null) objectsPublicItemProvider.dispose();
		if (bucketObjectsNotPublicItemProvider != null) bucketObjectsNotPublicItemProvider.dispose();
		if (onlyAuthorizedItemProvider != null) onlyAuthorizedItemProvider.dispose();
		if (file_aItemProvider != null) file_aItemProvider.dispose();
		if (folder_aItemProvider != null) folder_aItemProvider.dispose();
		if (metaDataItemProvider != null) metaDataItemProvider.dispose();
	}

}
