<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LayeredStyle" nsURI="http://co/edu/unal/mdd/photos/LayeredStyle"
    nsPrefix="co.edu.unal.mdd.photos.LayeredStyle">
  <eClassifiers xsi:type="ecore:EClass" name="LayeredStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layer" upperBound="-1"
        eType="#//Layer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relation" upperBound="-1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layersegment" upperBound="-1"
        eType="#//LayerSegment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLayer" eType="#//Layer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetLayer" eType="#//Layer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayerSegment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllowedToUse" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllowedToUseBelow" eSuperTypes="#//Relation"/>
</ecore:EPackage>
