<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SystemMetamodel" nsURI="http://co/edu/unal/mdd/photos/SystemMetamodel"
    nsPrefix="co.edu.unal.mdd.photos.SystemMetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoftGallery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arquitectura" lowerBound="1"
        eType="#//Arquitectura" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dominio" lowerBound="1"
        eType="#//Dominio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tecnologia" lowerBound="1"
        eType="#//Tecnología" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dominio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="registro" lowerBound="1"
        eType="#//Registro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autenticacion" lowerBound="1"
        eType="#//Autenticacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redsocial" lowerBound="1"
        eType="#//RedSocial" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arquitectura"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tecnología"/>
  <eClassifiers xsi:type="ecore:EClass" name="Autenticacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Registro">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crean" upperBound="-1"
        eType="#//Usuario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedSocial">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tieneUsuarios" lowerBound="1"
        upperBound="-1" eType="#//Usuario" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apellido" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usuario" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clave" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inicianSesion" upperBound="-1"
        eType="#//Autenticacion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posee" lowerBound="1" eType="#//Perfil"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modificar" lowerBound="1"
        eType="#//Perfil"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visualizan" lowerBound="1"
        upperBound="-1" eType="#//Album"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creanAlbum" lowerBound="1"
        upperBound="-1" eType="#//Album"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargar" upperBound="-1"
        eType="#//Foto"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="visualizar" upperBound="-1"
        eType="#//Foto"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Perfil">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descripcion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="muestranAlbum" lowerBound="1"
        upperBound="-1" eType="#//Album"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tieneFotos" upperBound="-1"
        eType="#//Foto" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foto">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ubicacion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
