<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SystemMetamodel" nsURI="http://co/edu/unal/mdd/photos/SystemMetamodel"
    nsPrefix="co.edu.unal.mdd.photos.SystemMetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="SoftGallery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arquitectura" lowerBound="1"
        eType="#//Arquitectura" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dominio" lowerBound="1"
        eType="#//Dominio" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tecnologia" lowerBound="1"
        eType="#//Tecnología" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dominio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usuarios" upperBound="-1"
        eType="#//Usuario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="galeriasFotos" upperBound="-1"
        eType="#//Fotos" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arquitectura">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ntier" lowerBound="1" eType="#//Ntier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tecnología"/>
  <eClassifiers xsi:type="ecore:EClass" name="Autenticacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Registro"/>
  <eClassifiers xsi:type="ecore:EClass" name="Usuario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tieneManejoPerfil" upperBound="-1"
        eType="#//manejoPerfil" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="puedeTener" lowerBound="1"
        eType="#//Registro" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="puedeAutenticarse" upperBound="-1"
        eType="#//Autenticacion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="poseeUnaGaleria" lowerBound="1"
        eType="#//Fotos"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="last_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile_description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fotos">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorias" lowerBound="1"
        upperBound="-1" eType="#//Categoria" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imagenes" upperBound="-1"
        eType="#//Imagen" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="manejoPerfil">
    <eStructuralFeatures xsi:type="ecore:EReference" name="acciones" upperBound="-1"
        eType="#//Acciones" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categoria">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Imagen">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tienenCategoria" lowerBound="1"
        eType="#//Categoria"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Acciones"/>
  <eClassifiers xsi:type="ecore:EClass" name="CrearAlbumes" eSuperTypes="#//Acciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crearCategoria" upperBound="-1"
        eType="#//Categoria"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizarAlbumes" eSuperTypes="#//Acciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="visualizarCategoria" lowerBound="1"
        upperBound="-1" eType="#//Categoria"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CargarFotos" eSuperTypes="#//Acciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cargarImagen" upperBound="-1"
        eType="#//Imagen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizarTodasFotos" eSuperTypes="#//Acciones"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditarPerfil" eSuperTypes="#//Acciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editarPerfil" upperBound="-1"
        eType="#//Fotos"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ntier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capas" upperBound="-1"
        eType="#//Capas" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciones" upperBound="-1"
        eType="#//Relaciones" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conexiones" upperBound="-1"
        eType="#//Conexiones" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capas"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relaciones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceRelation" eType="#//Capas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetRelation" eType="#//Capas"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conexiones">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceConection" eType="#//Capas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetConection" eType="#//Capas"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="REST" eSuperTypes="#//Conexiones"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConexionPostgres" eSuperTypes="#//Conexiones">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APIS3" eSuperTypes="#//Conexiones">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endpointUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secretKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bucketName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllowedToUse" eSuperTypes="#//Relaciones"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllowedToUseBellow" eSuperTypes="#//Relaciones"/>
  <eClassifiers xsi:type="ecore:EClass" name="Presentacion" eSuperTypes="#//Capas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentopresentacion" upperBound="-1"
        eType="#//SegmentoPresentacion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicaNegocio" eSuperTypes="#//Capas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentologica" upperBound="-1"
        eType="#//SegmentoLogica" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datos" eSuperTypes="#//Capas">
    <eStructuralFeatures xsi:type="ecore:EReference" name="segmentodatos" upperBound="-1"
        eType="#//SegmentoDatos" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View" eSuperTypes="#//SegmentoPresentacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//SegmentoPresentacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Action" eSuperTypes="#//SegmentoPresentacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" eSuperTypes="#//SegmentoLogica"/>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//SegmentoLogica"/>
  <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="#//SegmentoLogica"/>
  <eClassifiers xsi:type="ecore:EClass" name="Security" eSuperTypes="#//SegmentoLogica"/>
  <eClassifiers xsi:type="ecore:EClass" name="Postgres" eSuperTypes="#//SegmentoDatos"/>
  <eClassifiers xsi:type="ecore:EClass" name="S3" eSuperTypes="#//SegmentoDatos"/>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentoPresentacion"/>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentoLogica"/>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentoDatos"/>
</ecore:EPackage>
